name: SonarCloud

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:

  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Analyze with SonarCloud
        run: mvn -B clean verify sonar:sonar -Dsonar.projectKey=code4romania_expert-consultation-api -Dsonar.organization=code4romania -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
